{ config, lib, pkgs, username, ... }:

{
  imports = [
    # Generated by the NixOS installer on your machine — copy it next to this file.
    ./hardware-configuration.nix
  ];

  # ---------- Boot ----------
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ---------- Networking ----------
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;

  # ---------- Locale / time ----------
  time.timeZone = "Europe/Warsaw";
  i18n.defaultLocale = "en_US.UTF-8";

  # ---------- Nix ----------
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  nix.settings.auto-optimise-store = true; # hard-links identical store files, saves disk
  nixpkgs.config.allowUnfree = true; # required for NVIDIA userspace + vscode

  # Weekly store cleanup (your `cleanup` alias still works for manual runs)
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # ---------- NVIDIA (RTX 4070 Ti / Ada Lovelace) ----------
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;       # default on NixOS for driver > 535, set explicitly anyway
    powerManagement.enable = true;   # fixes suspend/resume memory issues
    open = true;                     # open kernel modules — recommended for Turing+ (your 4070 Ti qualifies)
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # ---------- Wayland / Hyprland session ----------
  programs.hyprland = {
    enable = true;
    withUWSM = true; # enables programs.uwsm — required, or the default UWSM session in SDDM dies instantly
  };

  # ---------- Display manager (login screen) ----------
  services.displayManager.ly.enable = true;

  environment.sessionVariables = {
    NIXOS_OZONE_WL = "1";                 # Electron/Chromium apps (code, brave) on Wayland
    ELECTRON_OZONE_PLATFORM_HINT = "auto";
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    # Cursor theme — set at system level so Hyprland itself sees it at startup
    XCURSOR_THEME = "Bibata-Modern-Ice";
    XCURSOR_SIZE = "24";
    HYPRCURSOR_THEME = "Bibata-Modern-Ice";
    HYPRCURSOR_SIZE = "24";
  };

  # ---------- Audio (PipeWire) ----------
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ---------- Shell ----------
  programs.zsh.enable = true; # system-level: registers zsh in /etc/shells

  # SSH agent for git/GitHub keys (ssh-add once per session)
  programs.ssh.startAgent = true;

  # Kills the biggest memory hog before the desktop hard-locks under OOM
  services.earlyoom.enable = true;

  # Wireshark: sets up dumpcap capture permissions — members of the
  # "wireshark" group can sniff without root. Includes tshark CLI.
  programs.wireshark.enable = true;

  # ---------- VirtualBox ----------
  virtualisation.virtualbox.host = {
    enable = true;
    enableExtensionPack = true; # USB 2.0/3.0 passthrough, RDP (unfree license)
  };

  # Lets prebuilt dynamically-linked binaries (e.g. vendor CLI installers) run on NixOS
  programs.nix-ld.enable = true;

  # ---------- User ----------
  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" "wireshark" "vboxusers" ];
    shell = pkgs.zsh;
    # Set your password after first rebuild:  passwd <username>
  };

  # ---------- Encrypted swap: random key per boot ----------
  # The installer created partition nvme1n1p3 but never formatted it, and the
  # generated hardware-configuration.nix references a LUKS container UUID that
  # doesn't exist — that caused the 90s dev-mapper timeout on every boot.
  # Fix: force-override swapDevices to the real partition with NixOS's native
  # random-key encryption. No prompt, encrypted at rest, no hibernation.
  swapDevices = lib.mkForce [
    {
      device = "/dev/disk/by-partuuid/4f37afb4-1a95-488b-9ef7-8b2c3b3dfe3f";
      randomEncryption.enable = true;
    }
  ];

  # ---------- SSH ----------
  services.openssh = {
    enable = true;
    # Later, once key auth works, harden with:
    # settings.PasswordAuthentication = false;
    # users.users.${username}.openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAA..." ];
  };

  # ---------- Tailscale ----------
  # WiFi is on an isolated VLAN and can't reach the wired network — Tailscale
  # tunnels around that, so you can SSH over WiFi or ethernet alike.
  services.tailscale.enable = true;

  # ---------- System packages ----------
  environment.systemPackages = with pkgs; [
    git
    curl
    wget
    wl-clipboard
    pavucontrol
    networkmanagerapplet
    # rpi-imager 2.x writes block devices directly and must run as root
    # (`pimager` wrapper script, see home.nix) — its pkexec self-elevation
    # hard-codes /usr/bin/pkexec, which doesn't exist on NixOS.
    rpi-imager
  ];

  # Auto-mounting of removable drives (USB sticks, SD cards) for file managers
  services.udisks2.enable = true;

  # ---------- Console / ly login screen ----------
  # NVIDIA mirrors ONE framebuffer across both displays, so force a common
  # mode (the Xiaomi's native res) — identical, centered console on both.
  # Big Terminus font keeps ly readable when the Samsung upscales it.
  # NOTE: connector names can renumber on driver updates (was DP-2/HDMI-A-3).
  boot.kernelParams = [ "video=DP-1:2560x1440" "video=HDMI-A-1:2560x1440" ];
  console = {
    font = "ter-u32n";
    packages = [ pkgs.terminus_font ];
  };

  # ---------- Fonts ----------
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
  ];

  # Default every font family to JetBrains Mono; Noto covers glyphs it lacks
  # (CJK, emoji) so nothing ever renders as tofu boxes.
  fonts.fontconfig.defaultFonts = {
    monospace = [ "JetBrainsMono Nerd Font" "Noto Color Emoji" ];
    sansSerif = [ "JetBrainsMono Nerd Font" "Noto Sans" "Noto Color Emoji" ];
    serif = [ "JetBrainsMono Nerd Font" "Noto Serif" "Noto Color Emoji" ];
    emoji = [ "Noto Color Emoji" ];
  };

  # ---------- GUI file manager ----------
  programs.thunar.enable = true;
  services.gvfs.enable = true;    # trash, network locations
  services.tumbler.enable = true; # file thumbnails

  # Don't touch after install — this matches the NixOS release you installed with.
  system.stateVersion = "26.05";
}
